### ISSUE TITLE
09 -- Revenge of the Nodes - Kim Mattiko

### ISSUE THREAD

**Issue by kmattiko** [TheIronYard--Orlando/2015--SUMMER--FEE#119] opened 2015-05-18 17:33 UTC
- [x] **Yak Shaving**
  - [x] _WIP Issue_ `09 -- Revenge of the Nodes`
    - [x] Link to PR in `USERNAME.github.io`
    - [x] Link to PR in `TheIronYard--Orlando/student-roster`
    - [x] Link to PR in `TIY-Assignments`
  - [x] _WIP Branch_
    - [x] `USERNAME.github.io:journal-week-2`
    - [x] `student-roster:master`
    - [x] `TIY-Assignments:09--revenge-of-the-nodes`
  - [x] _WIP Files_
    - `USERNAME.github.io`
      - `journal-week-2.md` (suggested)
      - `about/cascading-style-sheets.md`
    - `student-roster`
      - `2015-05/FEE/USERNAME.md` (for someone else)
    - `TIY-Assignments`
      - `NestedAccordion/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
      - `ViewModeSwitch/`
        - `index.html`
        - `styles.css`
        - `scripts.js`
    - `FullWidthTabs/`
      - `index.html`
      - `styles.css`
      - `scripts.js`
- [x] **Journal, Week 2**
  - [x] Brainstorming/Outline
  - [x] 1x :+1: + feedback!
  - [x] 2x :+1: + feedback!
- [x] **Reading CSS**
  - [x] Committed and pushed `about/cascading-style-sheets.md`
  - [x] Read _Learn Layout_!
  - [x] First 2 properties!
  - [x] Up to 5 properties!
  - [x] And then there were 8!
  - [x] All 10 in the bag!
- [ ] **Now It's Personal**
  - [x] Updated local `master` from `upstream:master`
  - [ ] Resolved conflicts...? WHY!?
  - [ ] Created new issue in `student-roster`...
- [ ] **Shaving the Night Away**
  - [x] Added `ViewModeSwitch` to the list...
  - [x] ...and gutted them all!
  - [x] Wired them back up again...
  - [ ] ...with Google Fonts, too!

**Comment by kmattiko** [comment] 2015-05-19 01:40
https://github.com/kmattiko/kmattiko.github.io/pull/5

**Comment by kmattiko** [comment] 2015-05-19 01:47
https://github.com/kmattiko/TIY-Assignments/pull/11

**Comment by kmattiko** [comment] 2015-05-19 12:16
https://github.com/TheIronYard--Orlando/student-roster/pull/41

**Comment by al-the-x** [comment] 2015-05-19 20:18
Your `student-roster` repo is a little wacky. There's a `student-roster/` directory that contains a dupe of all the files in the bottom of the repo.

Where is the gutting and rewiring for the other projects: Nested Accordion and Full Width Tabs?

**Comment by al-the-x** [comment] 2015-05-19 20:33
Please review and close.

**Closed as completed** 2015-05-19 20:53 UTC
Labels: Keep Practicing
